apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  labels:
    cloud: AWS
    region: 'us-east-1'
    cluster.open-cluster-management.io/clusterset: default
    vendor: OpenShift
  name: cluster-name
  namespace: cluster-name
spec:
  baseDomain: '{{ (fromSecret "cluster-provider-infra" "aws-creds" "baseDomain") | base64dec }}'
  clusterName: cluster-name
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    aws:
      credentialsSecretRef:
        name: aws-creds
      region: us-east-1
  provisioning:
    installConfigSecretRef:
      name: install-config
    sshPrivateKeySecretRef:
      name: ssh-privatekey
  pullSecretRef:
    name: rh-pull-secret
